import Head from "next/head";

function Home() {
  return (
    <>
      <Head>
        <title>Nextupgrad USA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../assets/logo.webp" />
      </Head>
      <div>
        <h1>Home Page !!</h1>
      </div>
    </>
  );
}

export default Home